version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '3000:3000'  # Next.js のデフォルトポート
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    command: npm run dev
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'  # Laravel の開発サーバーと同じポート
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:ランダムなキーをここに設定
    command: php artisan serve --host=0.0.0.0 --port=8000  # Laravel を直接起動
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
